const menAllClothes: any = [
  {
    id: 1,
    productType: "sneaker",
    productName: "NIKE MEN'S HUARACHE MULTICOLOUR SNEAKER",
    productDescription:
      "Leather and hemp accents add a textured, layered look. Inspired by water skiing, the upper’s stretchy fabric hugs your foot for an incredible feel. Originally designed for performance running, Nike Air cushioning delivers lasting comfort. Caged heel adds support and pairs with an elongated tongue to keep the early '90s look you love. Cushioned inner sleeve stretches to your foot for an oh-so-personalized fit.",
    productImage: "",
    productPrice: 2799.95,
    productColors: "MULTICOLOUR",
    productRoute: "",
    productGender: "Men",
  },
  {
    id: 2,
    productType: "sneaker",
    productName: "Air Jordan 1 Mid",
    productDescription:
      "Inspired by the original AJ1, this mid-top edition maintains the iconic look you love while choice colours and crisp leather give it a distinct identity.",
    productImage: "",
    productPrice: 2399.95,
    productColors: "Black/White/Fire Red",
    productRoute: "",
    productGender: "Men",
  },
  {
    id: 3,
    productType: "sneaker",
    productName: "Nike Alphafly 2",
    productDescription:
      "Once you take a few strides in the Nike Air Zoom Alphafly NEXT% 2, you'll never look at your favourite pair of old racing shoes the same way again. These rocket ships are made to help shave precious time off your personal records without surrendering the foundation you need to go the full distance. A thick, lightweight support system marries the 2 worlds of comfort and speed in holy running matrimony. Enjoy the greatest energy return of all our racing shoes while you chase your personal bests.",
    productImage: "",
    productPrice: 5899.95,
    productColors: "Total Orange/Bright Crimson/Ghost",
    productRoute: "",
    productGender: "Men",
  },
  {
    id: 4,
    productType: "sneaker",
    productName: "NikeCourt Air Zoom Pro",
    productDescription:
      "Harness the power of your serve in the NikeCourt Zoom Pro. Working in tandem with the Zoom Air unit, it has a full-length plate that acts like a springboard. Flexing with every step, it helps enhance energy return and increase stability. With a more linear, angular-shaped mesh and finish and a padded collar, this responsive design also helps keep your feet cool and comfortable during your toughest matches.",
    productImage: "",
    productPrice: 1999.95,
    productColors: "Black/White",
    productRoute: "",
    productGender: "Men",
  },
  {
    id: 5,
    productType: "sneaker",
    productName: "Air Jordan 13 Retro",
    productDescription:
      "The Air Jordan 13 Retro brings back the memorable game shoe that Michael Jordan wore during the '97–98 season, all the way to his 6th championship title. All the classic details are there like the quilted overlay, iconic sculpted midsole and holographic eye.",
    productImage: "",
    productPrice: 3699.95,
    productColors: "White/French Blue",
    productRoute: "",
    productGender: "Men",
  },
  {
    id: 6,
    productType: "sneaker",
    productName: "ALPHABOUNCE+ SUSTAINABLE BOUNCE",
    productDescription:
      "Go for that walk around the neighbourhood or head to the gym in a pair of adidas Alphabounce+ shoes. The mesh upper is soft and breathable to keep you comfortable as you go. A Bounce midsole makes the ride soft and springy while Cloudfoam on the heel cushions every step, so you can cruise smoothly through the day.",
    productImage: "",
    productPrice: 1899.0,
    productColors: "Grey Three",
    productRoute: "",
    productGender: "Men",
  },
  {
    id: 7,
    productType: "sneaker",
    productName: "OZELIA SHOES",
    productDescription:
      "With '90s running style at their core, these Ozelia Shoes have a bold look that's refreshed for today. Fluid lines give them a futuristic feel that's emphasised by a chunky silhouette. The textile upper is complemented with weldings for a premium look and feel. But these shoes aren't just about looks — Adiprene cushioning in the midsole adds all-day comfort. Made with a series of recycled materials, this upper features at least 50% recycled content. This product represents just one of our solutions to help end plastic waste.",
    productImage: "",
    productPrice: 2199.0,
    productColors: "Shadow Red",
    productRoute: "",
    productGender: "Men",
  },
  {
    id: 8,
    productType: "sneaker",
    productName: "OLD SKOOL SHOE",
    productDescription:
      "Featuring classic suede and textile uppers for a timeless look, the Vans Club Old Skool pays homage to our heritage while ensuring that this low top, lace-up shoe remains as iconic as ever. It also includes reinforced toe caps, supportive padded collars, and signature rubber waffle outsoles.",
    productImage: "",
    productPrice: 999,
    productColors: "Black/White",
    productRoute: "",
    productGender: "Men",
  },
  {
    id: 9,
    productType: "sneaker",
    productName: "CHECKERBOARD SK8-HI STACKED SHOES",
    productDescription:
      "The Checkerboard Sk8-Hi Stacked takes our legendary high top style to a whole new level. Literally. Highlighting oversized features and unexpected layers like platform bumpers, exaggerated outsoles, and translucent foxing tape, this elevated platform shoe updates an iconic favorite while maintaining all of the original Vans DNA-including the iconic sidestripe. It also includes lace-up suede and canvas uppers, an enlarged checkerboard print, and supportive padded collars.",
    productImage: "",
    productPrice: 1399,
    productColors: "Multi/true white",
    productRoute: "",
    productGender: "Men",
  },
  {
    id: 10,
    productType: "sneaker",
    productName: "Energen Tech Shoes",
    productDescription:
      "Fly through your morning run. Float through the rest of your day. These Reebok shoes help you do it all in comfort thanks to the lightweight, responsive FuelFoam midsole. Layered, seamless overlays on the upper provide targeted support where you need it most. A grippy rubber outsole lets you stride confidently in all conditions.",
    productImage: "",
    productPrice: 1199,
    productColors: "Vector navy",
    productRoute: "",
    productGender: "Men",
  },
  {
    id: 11,
    productType: "sneaker",
    productName: "More Buckets Shoes",
    productDescription:
      "CLASSIC REEBOK HOOPS SHOES WITH AN OVERSIZE VECTOR LOGO",
    productImage: "",
    productPrice: 1199,
    productColors: "Vector Navy/Orange Flare/Vector Blue",
    productRoute: "",
    productGender: "Men",
  },
  //   {
  //     id: 2,
  //     productType: "",
  //     productName: "",
  //     productDescription: "",
  //     productImage: "",
  //     productPrice: "",
  //     productColors: "",
  //     productRoute: "",
  //     productGender: "",
  //   },
];
